# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ethical_oversight_pb2 as ethical__oversight__pb2


class EthicalOversightStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EvaluateAction = channel.unary_unary(
                '/besai.EthicalOversight/EvaluateAction',
                request_serializer=ethical__oversight__pb2.ActionRequest.SerializeToString,
                response_deserializer=ethical__oversight__pb2.EthicalAssessment.FromString,
                )
        self.GetEthicalGuidelines = channel.unary_unary(
                '/besai.EthicalOversight/GetEthicalGuidelines',
                request_serializer=ethical__oversight__pb2.GuidelinesRequest.SerializeToString,
                response_deserializer=ethical__oversight__pb2.EthicalGuidelines.FromString,
                )
        self.LogEthicalDecision = channel.unary_unary(
                '/besai.EthicalOversight/LogEthicalDecision',
                request_serializer=ethical__oversight__pb2.EthicalDecisionLog.SerializeToString,
                response_deserializer=ethical__oversight__pb2.LogResponse.FromString,
                )


class EthicalOversightServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EvaluateAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEthicalGuidelines(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogEthicalDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EthicalOversightServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EvaluateAction': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateAction,
                    request_deserializer=ethical__oversight__pb2.ActionRequest.FromString,
                    response_serializer=ethical__oversight__pb2.EthicalAssessment.SerializeToString,
            ),
            'GetEthicalGuidelines': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEthicalGuidelines,
                    request_deserializer=ethical__oversight__pb2.GuidelinesRequest.FromString,
                    response_serializer=ethical__oversight__pb2.EthicalGuidelines.SerializeToString,
            ),
            'LogEthicalDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.LogEthicalDecision,
                    request_deserializer=ethical__oversight__pb2.EthicalDecisionLog.FromString,
                    response_serializer=ethical__oversight__pb2.LogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'besai.EthicalOversight', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EthicalOversight(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EvaluateAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/besai.EthicalOversight/EvaluateAction',
            ethical__oversight__pb2.ActionRequest.SerializeToString,
            ethical__oversight__pb2.EthicalAssessment.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEthicalGuidelines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/besai.EthicalOversight/GetEthicalGuidelines',
            ethical__oversight__pb2.GuidelinesRequest.SerializeToString,
            ethical__oversight__pb2.EthicalGuidelines.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LogEthicalDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/besai.EthicalOversight/LogEthicalDecision',
            ethical__oversight__pb2.EthicalDecisionLog.SerializeToString,
            ethical__oversight__pb2.LogResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
