# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: besai_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x62\x65sai_service.proto\x12\x05\x62\x65sai\"\x1d\n\x0cInputRequest\x12\r\n\x05input\x18\x01 \x01(\t\" \n\x0eOutputResponse\x12\x0e\n\x06output\x18\x01 \x01(\t\"\x1f\n\x0e\x45xploreRequest\x12\r\n\x05topic\x18\x01 \x01(\t\"!\n\x0f\x45xploreResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x1f\n\x0eInsightRequest\x12\r\n\x05topic\x18\x01 \x01(\t\"\"\n\x0fInsightResponse\x12\x0f\n\x07insight\x18\x01 \x01(\t\"!\n\x10ReasoningRequest\x12\r\n\x05query\x18\x01 \x01(\t\"#\n\x11ReasoningResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\x99\x02\n\x0c\x42\x65SAIService\x12<\n\x0cProcessInput\x12\x13.besai.InputRequest\x1a\x15.besai.OutputResponse\"\x00\x12>\n\x0b\x45xploreGRPC\x12\x15.besai.ExploreRequest\x1a\x16.besai.ExploreResponse\"\x00\x12\x42\n\x0fGenerateInsight\x12\x15.besai.InsightRequest\x1a\x16.besai.InsightResponse\"\x00\x12G\n\x10PerformReasoning\x12\x17.besai.ReasoningRequest\x1a\x18.besai.ReasoningResponse\"\x00\x62\x06proto3')



_INPUTREQUEST = DESCRIPTOR.message_types_by_name['InputRequest']
_OUTPUTRESPONSE = DESCRIPTOR.message_types_by_name['OutputResponse']
_EXPLOREREQUEST = DESCRIPTOR.message_types_by_name['ExploreRequest']
_EXPLORERESPONSE = DESCRIPTOR.message_types_by_name['ExploreResponse']
_INSIGHTREQUEST = DESCRIPTOR.message_types_by_name['InsightRequest']
_INSIGHTRESPONSE = DESCRIPTOR.message_types_by_name['InsightResponse']
_REASONINGREQUEST = DESCRIPTOR.message_types_by_name['ReasoningRequest']
_REASONINGRESPONSE = DESCRIPTOR.message_types_by_name['ReasoningResponse']
InputRequest = _reflection.GeneratedProtocolMessageType('InputRequest', (_message.Message,), {
  'DESCRIPTOR' : _INPUTREQUEST,
  '__module__' : 'besai_service_pb2'
  # @@protoc_insertion_point(class_scope:besai.InputRequest)
  })
_sym_db.RegisterMessage(InputRequest)

OutputResponse = _reflection.GeneratedProtocolMessageType('OutputResponse', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUTRESPONSE,
  '__module__' : 'besai_service_pb2'
  # @@protoc_insertion_point(class_scope:besai.OutputResponse)
  })
_sym_db.RegisterMessage(OutputResponse)

ExploreRequest = _reflection.GeneratedProtocolMessageType('ExploreRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXPLOREREQUEST,
  '__module__' : 'besai_service_pb2'
  # @@protoc_insertion_point(class_scope:besai.ExploreRequest)
  })
_sym_db.RegisterMessage(ExploreRequest)

ExploreResponse = _reflection.GeneratedProtocolMessageType('ExploreResponse', (_message.Message,), {
  'DESCRIPTOR' : _EXPLORERESPONSE,
  '__module__' : 'besai_service_pb2'
  # @@protoc_insertion_point(class_scope:besai.ExploreResponse)
  })
_sym_db.RegisterMessage(ExploreResponse)

InsightRequest = _reflection.GeneratedProtocolMessageType('InsightRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSIGHTREQUEST,
  '__module__' : 'besai_service_pb2'
  # @@protoc_insertion_point(class_scope:besai.InsightRequest)
  })
_sym_db.RegisterMessage(InsightRequest)

InsightResponse = _reflection.GeneratedProtocolMessageType('InsightResponse', (_message.Message,), {
  'DESCRIPTOR' : _INSIGHTRESPONSE,
  '__module__' : 'besai_service_pb2'
  # @@protoc_insertion_point(class_scope:besai.InsightResponse)
  })
_sym_db.RegisterMessage(InsightResponse)

ReasoningRequest = _reflection.GeneratedProtocolMessageType('ReasoningRequest', (_message.Message,), {
  'DESCRIPTOR' : _REASONINGREQUEST,
  '__module__' : 'besai_service_pb2'
  # @@protoc_insertion_point(class_scope:besai.ReasoningRequest)
  })
_sym_db.RegisterMessage(ReasoningRequest)

ReasoningResponse = _reflection.GeneratedProtocolMessageType('ReasoningResponse', (_message.Message,), {
  'DESCRIPTOR' : _REASONINGRESPONSE,
  '__module__' : 'besai_service_pb2'
  # @@protoc_insertion_point(class_scope:besai.ReasoningResponse)
  })
_sym_db.RegisterMessage(ReasoningResponse)

_BESAISERVICE = DESCRIPTOR.services_by_name['BeSAIService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INPUTREQUEST._serialized_start=30
  _INPUTREQUEST._serialized_end=59
  _OUTPUTRESPONSE._serialized_start=61
  _OUTPUTRESPONSE._serialized_end=93
  _EXPLOREREQUEST._serialized_start=95
  _EXPLOREREQUEST._serialized_end=126
  _EXPLORERESPONSE._serialized_start=128
  _EXPLORERESPONSE._serialized_end=161
  _INSIGHTREQUEST._serialized_start=163
  _INSIGHTREQUEST._serialized_end=194
  _INSIGHTRESPONSE._serialized_start=196
  _INSIGHTRESPONSE._serialized_end=230
  _REASONINGREQUEST._serialized_start=232
  _REASONINGREQUEST._serialized_end=265
  _REASONINGRESPONSE._serialized_start=267
  _REASONINGRESPONSE._serialized_end=302
  _BESAISERVICE._serialized_start=305
  _BESAISERVICE._serialized_end=586
# @@protoc_insertion_point(module_scope)
